# Generated by Django 3.1.5 on 2021-01-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(default='https://i.pinimg.com/originals/a6/98/a0/a698a0a05318d6753c67635c32b9a7ae.jpg'),
        ),
    ]
